# Generated by Django 2.2.7 on 2019-11-13 21:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EatFresh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='region',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='season',
        ),
        migrations.AddField(
            model_name='produce',
            name='seasonAndRegion',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
